project_id = "xsrmzzcmvhbqdjaxmmjj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-alert-email]
verify_jwt = false

[db]
port = 54322
shadow_port = 54320
major_version = 15